project:
  type: website

website:
  title: "Pedram Golnari"
  navbar:
    right:
      - text: Resume
        href: https://github.com/pgolnari/Blog/blob/master/CV-Pedram%20Golnari_2022.12.12.pdf
      - icon: github
        href: https://github.com/pgolnari/Blog
      - icon: twitter
        href: https://twitter.com/pgolnari

      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

