project:
  type: website

website:
  title: "*Pedram Golnari, MD*"
  site-url: https://pgolnari.netlify.app/
  description: "My website"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Pedram Golnari. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/pgolnari/
      - icon: twitter
        href: https://twitter.com/pgolnari
      - icon: envelope
        href: mailto:pgolnari@yahoo.com
  twitter-card:
    creator: "@pgolnari"
    card-style: summary_large_image
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Publications
        menu:
          - text: Books
            href: Publications/Books.qmd
          - text: Peer-reviewed papers
            href: Publications/Peer_reviewed.qmd
      - text: Resume
      - icon: github
        href: https://github.com/pgolnari/Website
      - icon: twitter
        href: https://twitter.com/pgolnari

format:
  html:
    theme: darkly
    css: styles.css
    link-external-newwindow: true
    toc: true

editor: visual

comments:
  giscus:
    repo: pgolnari/Website
