project:
  type: website

website:
  title: "*Pedram Golnari, MD*"
  site-url: https://pgolnari.netlify.app/
  description: "My website"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Pedram Golnari. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/pgolnari/
      - icon: twitter
        href: https://twitter.com/pgolnari
      - icon: envelope
        href: mailto:pgolnari@yahoo.com
  twitter-card:
    creator: "@pgolnari"
    card-style: summary_large_image
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Publications
        menu:
          - text: Book chapters
            href: Publications/Books.qmd
          - text: Peer-reviewed papers
            href: Publications/Peer_reviewed.qmd
      - text: CV
        href: https://pgolnari.github.io/CV-Pedram Golnari.pdf
      - text: Posts
        menu: 
          - text: Pre- vs Post-publication Peer Reviews
            href: Posts/Pre- vs Post-publication Peer Reviews.qmd
          - text: Importance of Data Sharing
            href: Posts/Importance of Data Sharing.qmd
          - text: Including Instructions When Sharing Data/Code
            href: Posts/Including Instructions When Sharing Data.qmd
      - icon: github
        href: https://github.com/pgolnari/Website
      - icon: twitter
        href: https://twitter.com/pgolnari

format:
  html:
    theme: darkly
    css: styles.css
    link-external-newwindow: true
    toc: true

editor: visual

