[build]
  ignore = "/bin/false"
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.108.0"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"